package com.kalus.viberschedule
import android.app.*
import android.content.*
import android.database.ContentObserver
import android.net.Uri
import android.os.*
import android.provider.MediaStore
import androidx.core.app.NotificationCompat
import java.util.concurrent.Executors
class ScheduleWatcherService:Service(){private val w=Executors.newSingleThreadExecutor();private val bot=Executors.newSingleThreadExecutor();@Volatile private var run=true;private var obs:ContentObserver?=null
 override fun onCreate(){super.onCreate();if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager::class.java).createNotificationChannel(NotificationChannel("kalus","Kalus",NotificationManager.IMPORTANCE_LOW));startForeground(2239,NotificationCompat.Builder(this,"kalus").setSmallIcon(android.R.drawable.ic_menu_today).setContentTitle("Kalus").setContentText("Очікую нові фото…").setOngoing(true).build());val p=getSharedPreferences("cfg",MODE_PRIVATE);if(p.getLong("since",0)==0L)p.edit().putLong("since",System.currentTimeMillis()/1000).apply();obs=object:ContentObserver(Handler(Looper.getMainLooper())){override fun onChange(s:Boolean,u:Uri?){scan()}};contentResolver.registerContentObserver(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,true,obs!!);bot.execute{botLoop()}}
 private fun scan(){w.execute{val p=getSharedPreferences("cfg",MODE_PRIVATE);val since=p.getLong("since",0);var newest=since;val pr=arrayOf(MediaStore.Images.Media._ID,MediaStore.Images.Media.DATE_ADDED);contentResolver.query(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,pr,"${MediaStore.Images.Media.DATE_ADDED} > ?",arrayOf(since.toString()),"${MediaStore.Images.Media.DATE_ADDED} ASC")?.use{c->while(c.moveToNext()){val id=c.getLong(0);val d=c.getLong(1);newest=maxOf(newest,d);ScheduleImageProcessor.process(this,ContentUris.withAppendedId(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,id))}};p.edit().putLong("since",newest).apply()}}
 private fun botLoop(){val p=getSharedPreferences("cfg",MODE_PRIVATE);while(run){val t=p.getString("botToken","").orEmpty();if(t.isBlank()){Thread.sleep(3000);continue};val us=TelegramSender.getUpdatesBlocking(t,p.getLong("off",0));for(u in us){p.edit().putLong("off",u.updateId+1).apply();var id=p.getString("chatId","").orEmpty();val cmd=u.text.substringBefore(' ').substringBefore('@').lowercase();if(cmd=="/start"&&id.isBlank()){id=u.chatId;p.edit().putString("chatId",id).apply()};if(id.isNotBlank()&&u.chatId!=id)continue;when(cmd){"/start"->TelegramSender.sendMessageBlocking(t,u.chatId,"👋 Kalus запущено!\n📚 Групи: М223/9 та М224/11\n/schedule /status /groups /ping");"/ping"->TelegramSender.sendMessageBlocking(t,u.chatId,"🟢 Kalus online");"/groups"->TelegramSender.sendMessageBlocking(t,u.chatId,"🎓 ${p.getString("targets","М223/9,М224/11")}");"/status"->TelegramSender.sendMessageBlocking(t,u.chatId,"🟢 Моніторинг працює");"/schedule"->{val f=java.io.File(filesDir,"last_schedule.jpg");if(f.exists())TelegramSender.sendPhotoBlocking(t,u.chatId,f.readBytes(),"📚 Останній розклад")else TelegramSender.sendMessageBlocking(t,u.chatId,"📭 Розкладу ще немає")}}}}}
 override fun onDestroy(){obs?.let{contentResolver.unregisterContentObserver(it)};run=false;w.shutdownNow();bot.shutdownNow();super.onDestroy()};override fun onBind(i:Intent?)=null}
